[package]
name = "valhalla-client"
version = "0.1.1"
edition = "2021"
description = "API client for the Valhalla routing engine"
authors = ["Jelmer Vernooĳ <jelmer@jelmer.uk>"]
license = "Apache-2.0"
repository = "https://github.com/jelmer/valhalla-client-rs"

[dependencies]
geo-types = "0.7"
gpx = { version = "0.10", optional = true }
log = "0.4.22"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_repr = "0.1.19"
url = "2.5.2"

[features]
default = ["gpx"]
gpx = ["dep:gpx"]
