[package]
name = "valhalla-client"
version = "0.1.1"
edition = "2021"
description = "API client for the Valhalla routing engine"
authors = ["Jelmer Vernooĳ <jelmer@jelmer.uk>"]
license = "Apache-2.0"
repository = "https://github.com/jelmer/valhalla-client-rs"

[dependencies]
geo-types = "0.7.10"
gpx = { version = "0.9.1", optional = true }
log = "0.4.21"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
serde_repr = "0.1.14"
url = "2.4.0"

[features]
default = ["gpx"]
gpx = ["dep:gpx"]
